name: CI

on:
  push:
    branches: [main, develop, frontend-enhancements]
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r chatmind/pipeline/requirements.txt
      - name: Compile pipeline
        run: python -m compileall -q chatmind/pipeline

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install and build
        working-directory: chatmind/frontend
        run: |
          npm ci || npm i
          npm run build

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docs (mkdocs)
        run: |
          pip install mkdocs-material
          mkdocs build
